
FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y openssh-client openssh-server tcpdump nano && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /var/run/sshd

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
